import { TypographyOptions } from '@mui/material/styles/createTypography';
import '@fontsource/roboto';
import '@fontsource/open-sans';
import '@fontsource-variable/open-sans';

export const typography: TypographyOptions = {
  fontSize: 16,
  fontWeightLight: 300,
  fontWeightRegular: 400,
  fontWeightMedium: 500,
  fontWeightBold: 600,
  htmlFontSize: 16, // NO CAMBIAR
  fontFamily: [
    'Roboto',
    '"Open Sans"',
    '"Open Sans Variable"',
    '"Helvetica Neue"',
    'Arial',
    'sans-serif',
    '-apple-system',
  ].join(','),
  h1: {
    fontFamily: 'Roboto',
    // fontSize: '48px',
    // letterSpacing: '0px',
    // lineHeight: '44px',
    fontSize: '2.375rem',
    letterSpacing: '0rem',
    lineHeight: '2.75rem',
    fontWeight: 900,
  },
  h2: {
    fontFamily: 'Roboto',
    // fontSize: '28px',
    // letterSpacing: '0px',
    // lineHeight: '34px',
    fontSize: '1.75rem',
    letterSpacing: '0rem',
    lineHeight: '2.125rem',
    fontWeight: 700,
  },
  h3: {
    fontFamily: 'Roboto',
    // fontSize: '21px',
    // letterSpacing: '0px',
    // lineHeight: '28px',
    fontSize: '1.3125rem',
    letterSpacing: '0rem',
    lineHeight: '1.75rem',
    fontWeight: 700,
  },
  h4: {
    fontFamily: 'Roboto',
    // fontSize: '19px',
    // letterSpacing: '0px',
    // lineHeight: '26px',
    fontSize: '1.1875rem',
    letterSpacing: '0rem',
    lineHeight: '1.5rem',
    fontWeight: 700,
  },
  h5: {
    fontFamily: 'Open Sans',
    // fontSize: '18px',
    // letterSpacing: '0',
    // lineHeight: '24px',
    fontSize: '1.125rem',
    letterSpacing: '0',
    lineHeight: '1.5rem',
    fontWeight: 600,
  },
  h6: {
    fontFamily: 'Open Sans',
    // fontSize: '16px',
    // letterSpacing: '0px',
    // lineHeight: '24px',
    fontSize: '1rem',
    letterSpacing: '0rem',
    lineHeight: '1.5rem',
    fontWeight: 700,
  },
  body1: {
    fontFamily: 'Open Sans',
    // fontSize: '16px',
    // letterSpacing: '0px',
    // lineHeight: '24px',
    fontSize: '1rem',
    letterSpacing: '0rem',
    lineHeight: '1.5rem',
    fontWeight: 400,
  },
  body2: {
    fontFamily: 'Open Sans',
    // fontSize: '14px',
    // letterSpacing: '0px',
    // lineHeight: '20px',
    fontSize: '0.8125rem',
    letterSpacing: '0rem',
    lineHeight: '1.25rem',
    fontWeight: 400,
  },
  subtitle1: {
    fontFamily: 'Open Sans',
    // fontSize: '18px',
    // letterSpacing: '0px',
    // lineHeight: '28px',
    fontSize: '1.125rem',
    letterSpacing: '0.4375rem',
    lineHeight: '1.25rem',
    fontWeight: 400,
  },
  button: {
    fontFamily: 'Open Sans',
    // fontSize: '16px',
    // letterSpacing: '0px',
    // lineHeight: '20px',
    fontSize: '1rem',
    letterSpacing: '0rem',
    lineHeight: '1.25rem',
    textTransform: 'capitalize',
    fontWeight: 600,
  },
  overline: {
    fontFamily: 'Open Sans',
    // fontSize: '14px',
    // letterSpacing: '2px',
    // lineHeight: '16px',
    fontSize: '0.8rem',
    letterSpacing: '0.125rem',
    lineHeight: '1rem',
    fontWeight: 400,
  },
  caption: {
    fontFamily: 'Open Sans',
    // fontSize: '12px',
    // letterSpacing: '2px',
    // lineHeight: '16px',
    fontSize: '0.75rem',
    letterSpacing: '0.125rem',
    lineHeight: '1rem',
    fontWeight: 400,
  },
};
